apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "space-app.fullname" . }}-frontend
  labels:
    {{- include "space-app.labels" . | nindent 4 }}
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "space-app.labels" . | nindent 8 }}
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ include "space-app.frontend.image" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
