apiVersion: v1
kind: Secret
metadata:
  name: {{ include "space-app.fullname" . }}-secret
  labels:
    {{- include "space-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_TOKEN: {{ .Values.secret.apiToken | quote }}
